Mmaxi/auth0
ingsis-group10-2024/snippet-runner pull request #2
Opened 2024-10-22 22:25 UTC by MaxiMaglio

2024-10-22 22:38 UTC, AlbertoPizzi approved these changes
LGTM

2024-10-22 23:51 UTC, CCatalini requested changes

2024-10-22 23:51 UTC, CCatalini commented on src/main/kotlin/auth/SecurityConfig.kt
> +class SecurityConfig {
Faltaria agregar el JwtDecoder

2024-10-24 13:00 UTC, CCatalini approved these changes

2024-10-24 13:00 UTC, merged